spring:
  application:
    name: user-service
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/userdb?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: secret

management:
  endpoints:
    web:
      exposure.include: beans, env, health, info, metrics, mappings
  endpoint:
    health:
      show-details: always

springdoc:
  show-actuator: true
  swagger-ui:
    groups-order: DESC

---
spring:
  profiles: test
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url:      # \
    username: #  ) they will be set dynamically by AbstractTestcontainers
    password: # /
